name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - name: Fix lint issues
        run: bun run lint:fix
      - uses: autofix-ci/action@bee19d72e71787c12ca0f29de72f2833e437e4c9
        with:
          commit-message: "chore: apply automated fixes"
